blank_issues_enabled: false
contact_links:
  - name: ALZ bugs / features / questions (everything goes here)
    url: https://github.com/Azure/Azure-Landing-Zones/issues/new/choose
    about: Centralized repo for all Azure landing zone (ALZ) bugs, features, and questions (new for 2026)
